/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nibsa_nixtla_demo_capture_eco_DemoNativeInterface */

#include "nixtla-audio.h"
#include <stdio.h>		//NULL
#include <stdlib.h>		//malloc, free

//

#include <android/log.h>
#define PRINTF(STR_FMT, ...)			__android_log_print(ANDROID_LOG_INFO, "NixDemo", STR_FMT, ##__VA_ARGS__)
#define PRINTF_INFO(STR_FMT, ...)		__android_log_print(ANDROID_LOG_INFO, "NixDemo", STR_FMT, ##__VA_ARGS__)
#define PRINTF_ERROR(STR_FMT, ...)		__android_log_print(ANDROID_LOG_ERROR, "NixDemo", "ERROR, "STR_FMT, ##__VA_ARGS__)
#define PRINTF_WARNING(STR_FMT, ...)	__android_log_print(ANDROID_LOG_WARN, "NixDemo", "WARNING, "STR_FMT, ##__VA_ARGS__)

//

#define NIX_DEMO_BUFFERS_PER_SECOND	3

STNix_Engine nix;
NixUI16 sourceStream = 0;

void bufferCapturedCallback(STNix_Engine* eng, void* userdata, const STNix_audioDesc audioDesc, const NixUI8* audioData, const NixUI32 audioDataBytes, const NixUI32 audioDataSamples){
	const NixUI16 iSource = *((NixUI16*)userdata);
	const NixUI16 iBuffer = nixBufferWithData(eng, &audioDesc, audioData, audioDataBytes);
	if(iBuffer==0){
		PRINTF_ERROR("bufferCapturedCallback, nixBufferWithData failed for iSource(%d)\n", iSource);
	} else {
		if(nixSourceStreamAppendBuffer(eng, iSource, iBuffer)){
			//PRINTF_INFO("bufferCapturedCallback, source(%d) new buffer(%d) attached\n", iSource, iBuffer);
		} else {
			PRINTF_WARNING("bufferCapturedCallback, ERROR attaching new buffer buffer(%d) to source(%d)\n", iBuffer, iSource);
		}
		nixBufferRelease(eng, iBuffer);
	}
}

JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeInit(JNIEnv *pEnv, jclass pClass){
	if(!nixInit(&nix, 8)){
		PRINTF_ERROR("nixInit failed\n");
	} else {
		return JNI_TRUE;
	}
	return JNI_FALSE;
}

JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeFinalize(JNIEnv *pEnv, jclass pClass){
	nixCaptureStop(&nix);
	nixCaptureFinalize(&nix);
	nixSourceRelease(&nix, sourceStream);
	nixFinalize(&nix);
}

JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeTick(JNIEnv *pEnv, jclass pClass){
	nixTick(&nix);
}

JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeActionCapture(JNIEnv *pEnv, jclass pClass, jint pChannels, jint pSampleRate, jint pBitsPerSample){
	if(nixCaptureIsOnProgress(&nix)){
		PRINTF_INFO("Capture stopping\n");
		nixCaptureStop(&nix);
		nixCaptureFinalize(&nix);
		if(sourceStream!=0){
			nixSourceStop(&nix, sourceStream);
			nixSourceRelease(&nix, sourceStream);
			sourceStream = 0;
		}
		PRINTF_INFO("Capture stopped\n");
		return JNI_TRUE;
	} else {
		//Source for stream eco (play the captured audio)
		sourceStream = nixSourceAssignStream(&nix, NIX_TRUE, 0, NULL, NULL, NIX_DEMO_BUFFERS_PER_SECOND, NULL, NULL);
		if(sourceStream==0){
			PRINTF_ERROR("nixSourceAssign failed\n");
		} else {
			nixSourcePlay(&nix, sourceStream);
			//Init the capture
			STNix_audioDesc audioDesc;
			audioDesc.samplesFormat		= ENNix_sampleFormat_int;
			audioDesc.channels			= pChannels;
			audioDesc.bitsPerSample		= pBitsPerSample;
			audioDesc.samplerate		= pSampleRate;
			audioDesc.blockAlign		= (audioDesc.bitsPerSample / 8) * audioDesc.channels;
			if(!nixCaptureInit(&nix, &audioDesc, NIX_DEMO_BUFFERS_PER_SECOND, audioDesc.samplerate / NIX_DEMO_BUFFERS_PER_SECOND, &bufferCapturedCallback, &sourceStream)){
				PRINTF_ERROR("nixCaptureInit failed for channels(%d) bitsPerSample(%d), samplerate(%d)\n", audioDesc.channels, audioDesc.bitsPerSample, audioDesc.samplerate);
			} else {
				if(!nixCaptureStart(&nix)){
					PRINTF_ERROR("nixCaptureStart failed");
				} else {
					PRINTF_INFO("Capture started\n");
					return JNI_TRUE;
				}
				nixCaptureFinalize(&nix);
			}
		}
	}
	return JNI_FALSE;
}


JNIEXPORT jstring JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeGetStatusLog(JNIEnv *pEnv, jclass pClass){
	char strTmp[4096] = "";
	//
	STNix_StatusDesc nixStatusDesc;
	nixGetStatusDesc(&nix, &nixStatusDesc);
	sprintf(&strTmp[strlen(strTmp)], "%d sources (%d assigned)\n", nixStatusDesc.countSources, nixStatusDesc.countSourcesAssigned);
	sprintf(&strTmp[strlen(strTmp)], "%d play buffers", nixStatusDesc.countPlayBuffers);
	if(nixStatusDesc.sizePlayBuffers!=0){
		sprintf(&strTmp[strlen(strTmp)], " (%d KB", (nixStatusDesc.sizePlayBuffers / 1024));
		if(nixStatusDesc.sizePlayBuffersAtSW == 0){
			sprintf(&strTmp[strlen(strTmp)], " at HW)\n");
		} else if (nixStatusDesc.sizePlayBuffersAtSW == nixStatusDesc.sizePlayBuffers){
			sprintf(&strTmp[strlen(strTmp)], " at SW)\n");
		} else {
			sprintf(&strTmp[strlen(strTmp)], ")\n");
			sprintf(&strTmp[strlen(strTmp)], "   (%d KBs SW, %d KBs HW)\n", (nixStatusDesc.sizePlayBuffersAtSW / 1024),  ((nixStatusDesc.sizePlayBuffers - nixStatusDesc.sizePlayBuffersAtSW) / 1024));
		}
	} else {
		sprintf(&strTmp[strlen(strTmp)], "\n");
	}
	if(nixStatusDesc.countRecBuffers!=0){
		sprintf(&strTmp[strlen(strTmp)], "%d rec buffers (%d KB", nixStatusDesc.countRecBuffers, (nixStatusDesc.sizeRecBuffers / 1024));
		if(nixStatusDesc.sizeRecBuffersAtSW == 0){
			sprintf(&strTmp[strlen(strTmp)], " all HW)\n");
		} else if(nixStatusDesc.sizeRecBuffersAtSW == nixStatusDesc.sizeRecBuffers){
			sprintf(&strTmp[strlen(strTmp)], " all SW)\n");
		} else {
			sprintf(&strTmp[strlen(strTmp)], ")\n");
			sprintf(&strTmp[strlen(strTmp)], "   (%d KBs SW, %d KBs HW)\n", (nixStatusDesc.sizeRecBuffersAtSW / 1024),  ((nixStatusDesc.sizeRecBuffers - nixStatusDesc.sizeRecBuffersAtSW) / 1024));
		}
	}
	//
	return (*pEnv)->NewStringUTF(pEnv, strTmp); // C style string to Java String
}



