/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface */

#ifndef _Included_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
#define _Included_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeFinalize
  (JNIEnv *, jclass);

/*
 * Class:     com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
 * Method:    nativeTick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeTick
  (JNIEnv *, jclass);

/*
 * Class:     com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface
 * Method:    nativeActionCapture
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeActionCapture
  (JNIEnv *, jclass, jint, jint, jint);

JNIEXPORT jstring JNICALL Java_com_nibsa_nixtla_android_demo_captureeco_DemoNativeInterface_nativeGetStatusLog
(JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
