/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nibsa_nixtla_demo_play_wav_DemoNativeInterface */

#include "nixtla-audio.h"
#include <stdio.h>		//NULL
#include <stdlib.h>		//malloc, free
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>
#define PRINTF_INFO(STR_FMT, ...)		__android_log_print(ANDROID_LOG_INFO, "NixDemo", STR_FMT, ##__VA_ARGS__)
#define PRINTF_ERROR(STR_FMT, ...)		__android_log_print(ANDROID_LOG_ERROR, "NixDemo", "ERROR, "STR_FMT, ##__VA_ARGS__)
#define PRINTF_WARNING(STR_FMT, ...)	__android_log_print(ANDROID_LOG_WARN, "NixDemo", "WARNING, "STR_FMT, ##__VA_ARGS__)

#include "../../../../src/c/demos/utilLoadWavAndroid.c"

STNix_Engine nix;

typedef struct STFileStatus_ {
	const char* fileName;
	NixUI16		source;
} STFileStatus;

STFileStatus files[] = {
		{"beat_mono_08_08000.wav", 0},
		{"beat_mono_08_11025.wav", 0},
		{"beat_mono_08_22050.wav", 0},
		{"beat_mono_08_44100.wav", 0},
		{"beat_mono_16_08000.wav", 0},
		{"beat_mono_16_11025.wav", 0},
		{"beat_mono_16_22050.wav", 0},
		{"beat_mono_16_44100.wav", 0},
		{"beat_mono_24_08000.wav", 0},
		{"beat_mono_24_11025.wav", 0},
		{"beat_mono_24_22050.wav", 0},
		{"beat_mono_24_44100.wav", 0},
		{"beat_mono_32_08000.wav", 0},
		{"beat_mono_32_11025.wav", 0},
		{"beat_mono_32_22050.wav", 0},
		{"beat_mono_32_44100.wav", 0},
		{"beat_stereo_08_08000.wav", 0},
		{"beat_stereo_08_11025.wav", 0},
		{"beat_stereo_08_22050.wav", 0},
		{"beat_stereo_08_44100.wav", 0},
		{"beat_stereo_16_08000.wav", 0},
		{"beat_stereo_16_11025.wav", 0},
		{"beat_stereo_16_22050.wav", 0},
		{"beat_stereo_16_44100.wav", 0},
		{"beat_stereo_24_08000.wav", 0},
		{"beat_stereo_24_11025.wav", 0},
		{"beat_stereo_24_22050.wav", 0},
		{"beat_stereo_24_44100.wav", 0},
		{"beat_stereo_32_08000.wav", 0},
		{"beat_stereo_32_11025.wav", 0},
		{"beat_stereo_32_22050.wav", 0},
		{"beat_stereo_32_44100.wav", 0}
};

JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_playwav_DemoNativeInterface_nativeInit(JNIEnv *pEnv, jclass pClass){
	jboolean success = JNI_FALSE;
	if(nixInit(&nix, 8)==0){
		PRINTF_ERROR("nixInit failed.\n");
	} else {
		PRINTF_INFO("nixInit success.\n");
		nixPrintCaps(&nix);
		success = JNI_TRUE;
	}
	return success;
}

JNIEXPORT jboolean JNICALL Java_com_nibsa_nixtla_android_demo_playwav_DemoNativeInterface_nativeActionOnWav(JNIEnv *pEnv, jclass pClass, jobject assetManager, jstring pWavPath, jboolean repeat, jfloat volume){
	jboolean success = JNI_FALSE;
	const char* strWavPath = (*pEnv)->GetStringUTFChars(pEnv, pWavPath, 0);
	STNix_audioDesc audioDesc;
	NixUI8* audioData = NULL; NixUI32 audioDataBytes;
	//Look for STFileStatus index
	NixSI32 i, indexFound = -1; const NixSI32 size = (sizeof(files) / sizeof(STFileStatus));
	for(i=0; i<size; i++){
		const char* str = files[i].fileName;
		const char* str2 = strWavPath;
		while((*str)!=0 && (*str2)!=0){
			if((*str)!=(*str2)) break;
			str++; str2++;
		}
		if((*str)==(*str2)){
			indexFound = i;
			break;
		}
	}
	//Retrieve STFileStatus
	if(indexFound==-1){
		PRINTF_ERROR("Couldnt retrieve status data for: '%s'\n", strWavPath);
	} else {
		NixUI16 iSourceWav, iBuffer;
		STFileStatus* status = &files[indexFound];
		//Stop previous source
		if(status->source!=0){
			nixSourceStop(&nix, status->source);
			nixSourceRelease(&nix, status->source);
			status->source = 0;
		}
		//Load and play wav
		if(loadDataFromWavFile(pEnv, assetManager, strWavPath, &audioDesc, &audioData, &audioDataBytes)==0){
			PRINTF_ERROR("WAV file load failed.\n");
		} else {
			PRINTF_INFO("WAV file loaded.\n");
			iSourceWav = nixSourceAssignStatic(&nix, NIX_TRUE, 0, NULL, NULL);
			if(iSourceWav==0){
				PRINTF_ERROR("Source assign failed.\n");
			} else {
				PRINTF_INFO("Source(%d) assigned and retained.\n", iSourceWav);
				iBuffer = nixBufferWithData(&nix, &audioDesc, audioData, audioDataBytes);
				if(iBuffer==0){
					PRINTF_ERROR("Buffer assign failed.\n");
				} else {
					PRINTF_INFO("Buffer(%d) loaded with data and retained.\n", iBuffer);
					if(nixSourceSetBuffer(&nix, iSourceWav, iBuffer)==0){
						PRINTF_ERROR("Buffer-to-source linking failed.\n");
					} else {
						PRINTF_INFO("Buffer(%d) linked with source(%d).\n", iBuffer, iSourceWav);
						nixSourceSetRepeat(&nix, iSourceWav, repeat);
						nixSourceSetVolume(&nix, iSourceWav, volume);
						nixSourcePlay(&nix, iSourceWav);
						nixSourceRetain(&nix, iSourceWav);
						status->source = iSourceWav;
						success = JNI_TRUE;
					}
					nixBufferRelease(&nix, iBuffer);
				}
				nixSourceRelease(&nix, iSourceWav);
			}
		}
		if(audioData!=NULL) free(audioData); audioData = NULL;
	}
	(*pEnv)->ReleaseStringUTFChars(pEnv, pWavPath, strWavPath);
	return success;
}

JNIEXPORT jstring JNICALL Java_com_nibsa_nixtla_android_demo_playwav_DemoNativeInterface_nativeGetStatusLog(JNIEnv *pEnv, jclass pClass){
	char strTmp[4096] = "";
	//
	STNix_StatusDesc nixStatusDesc;
	nixGetStatusDesc(&nix, &nixStatusDesc);
	sprintf(&strTmp[strlen(strTmp)], "%d sources (%d assigned)\n", nixStatusDesc.countSources, nixStatusDesc.countSourcesAssigned);
	sprintf(&strTmp[strlen(strTmp)], "%d play buffers", nixStatusDesc.countPlayBuffers);
	if(nixStatusDesc.sizePlayBuffers!=0){
		sprintf(&strTmp[strlen(strTmp)], " (%d KB", (nixStatusDesc.sizePlayBuffers / 1024));
		if(nixStatusDesc.sizePlayBuffersAtSW == 0){
			sprintf(&strTmp[strlen(strTmp)], " at HW)\n");
		} else if (nixStatusDesc.sizePlayBuffersAtSW == nixStatusDesc.sizePlayBuffers){
			sprintf(&strTmp[strlen(strTmp)], " at SW)\n");
		} else {
			sprintf(&strTmp[strlen(strTmp)], ")\n");
			sprintf(&strTmp[strlen(strTmp)], "   (%d KBs SW, %d KBs HW)\n", (nixStatusDesc.sizePlayBuffersAtSW / 1024),  ((nixStatusDesc.sizePlayBuffers - nixStatusDesc.sizePlayBuffersAtSW) / 1024));
		}
	}
	if(nixStatusDesc.countRecBuffers!=0){
		sprintf(&strTmp[strlen(strTmp)], "%d rec buffers (%d KB", nixStatusDesc.countRecBuffers, (nixStatusDesc.sizeRecBuffers / 1024));
		if(nixStatusDesc.sizeRecBuffersAtSW == 0){
			sprintf(&strTmp[strlen(strTmp)], " all HW)\n");
		} else if(nixStatusDesc.sizeRecBuffersAtSW == nixStatusDesc.sizeRecBuffers){
			sprintf(&strTmp[strlen(strTmp)], " all SW)\n");
		} else {
			sprintf(&strTmp[strlen(strTmp)], ")\n");
			sprintf(&strTmp[strlen(strTmp)], "   (%d KBs SW, %d KBs HW)\n", (nixStatusDesc.sizeRecBuffersAtSW / 1024),  ((nixStatusDesc.sizeRecBuffers - nixStatusDesc.sizeRecBuffersAtSW) / 1024));
		}
	}
	//
	return (*pEnv)->NewStringUTF(pEnv, strTmp); // C style string to Java String
}

JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_playwav_DemoNativeInterface_nativeFinalize(JNIEnv *pEnv, jclass pClass){
	nixFinalize(&nix);
}

JNIEXPORT void JNICALL Java_com_nibsa_nixtla_android_demo_playwav_DemoNativeInterface_nativeTick(JNIEnv *pEnv, jclass pClass){
	nixTick(&nix);
}


